name: Main

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  
  prepare:

    runs-on: macos-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Log current Swift version
      run: swift --version

    - name: Run 'setup' script
      run: cd ./.setup && swift run && cd ./..

    - name: Install infrastructure dependencies via Bundler
      run: bundle install

    - name: Reconfigure project via Fastlane
      run: bundle exec fastlane reconfigureProject